name: Code Quality Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check Node.js version
      run: node -v

    - name: Check npm version
      run: npm -v

    - name: Verify package integrity
      run: npm audit check

    - name: Validate JSON files
      run: |
        # Check package.json syntax
        node -e "console.log('Validating package.json...'); JSON.parse(require('fs').readFileSync('package.json')); console.log('✓ package.json is valid');"
        
        # Check package-lock.json syntax if it exists
        if [ -f "package-lock.json" ]; then
          node -e "console.log('Validating package-lock.json...'); JSON.parse(require('fs').readFileSync('package-lock.json')); console.log('✓ package-lock.json is valid');"
        fi

    - name: Final status
      run: echo "Code quality check completed successfully!"
